export enum ERROR_CODES {
  'USERNAME_OR_PASSWORD_INCORRECT' = 2132,
  'USER_IS_ALREADY_REGISTERED' = 2133,
  'EMAIL_VERIFY_HASH_DOES_NOT_MATCH' = 2134,
  'DATA_NOT_FOUND' = 2135,
  'NOT_ENOUGH_STARS' = 2136,
  'REQUEST_ALREADY_EXISTS' = 2137,
}
